version: '3.1'
services:
  wordpress:
    image: wordpress:5.5.3-php7.4-apache
    network_mode: host
    environment:
      WORDPRESS_URL: 192.168.145.132
      WORDPRESS_DB_HOST: 192.168.145.132
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wpdb
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - "./wp-init.sh:/usr/local/bin/apache2-custom.sh"
    - "./ultimate-member:/var/www/html/wp-content/plugins/ultimate-member"      
    - "./wp-cli.phar:/bin/wp"
    command: apache2-custom.sh
  db:
    image: mysql:5.7
    network_mode: host
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: wppassword
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s
